sonar.projectKey=dennismorales12_proyecto-final-control-calidad-2026-kmiss
sonar.organization=dennismorales12
sonar.projectName=Proyecto Final Control de Calidad 2026 KMISS
sonar.sources=backend,frontend/src,db
sonar.tests=backend/src,frontend/src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx
sonar.exclusions=**/node_modules/**,frontend/dist/**,**/coverage/**,**/*.test.js,**/*.test.jsx
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300

